## Code Setup

This section will import the pandas library, which we will utilize throughout the rest of the project.

In [2]:
# Importing pandas library

import pandas as pd

## Importing Data

This section will import the Nebraska data file and then use different functions to view the data.

In [4]:
# Read in the Nebraska data file

nebraska_data = pd.read_csv('Nebraska_Violations_Formatted.csv')

In [6]:
# Make the data a dataframe

nebraska_data = pd.DataFrame(nebraska_data)

In [8]:
# Print the data

print(nebraska_data)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

In [42]:
# Utilizing the .head() function to view the first 10 rows of the data

nebraska_data.head(10)

,pws_id,pws_name,epa_region_code,primacy_agency,pws_type,owner_type,primary_source,activity_status,season_end_date,population,...,season_start_date,last_reported,submission_quarter,return_to_compliance_date,contaminant_code,submission_year,major_violation,connections,first_reported,submission_year.1
0,NE3120835,LITTLE USA,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,200,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
1,NE3121452,ELKHORN SHORES,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,35,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
2,NE3121245,DRIFTWOOD INN,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,25,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
3,NE3150475,TYSON FRESH MEATS INC MADISON,Region 7,Nebraska,NTNCWS,State,Ground water,Active,NaN,1100,...,45170,45199.0,Known,NaN,NaN,NaN,Y,NaN,3,45244
4,NE3121401,SANDY POINTE LAKE DEVELOPMENT,Region 7,Nebraska,CWS,State,Ground water,Active,NaN,100,...,45139,45169.0,Known,NaN,SIF,State Public Notification received,Y,NaN,3,45244
5,NE3150672,FORT HARTSUFF SHP - NG & PC,Region 7,Nebraska,TNCWS,State,Ground water,Active,NaN,45,...,45139,45169.0,Returned to Compliance,45188.0,SOX,State Compliance achieved,Y,NaN,3,45244
6,NE3101910,"SHELTON, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,1059,...,45139,45169.0,Known,NaN,SIE,State Public Notification requested,Y,NaN,3,45244
7,NE3150566,SARPY CO DIST 46 - PLATTEVIEW HIGH,Region 7,Nebraska,NTNCWS,State,Ground water,Active,NaN,614,...,45139,45169.0,Known,NaN,SIE,State Public Notification requested,Y,NaN,3,45244
8,NE3103105,"WOOD LAKE, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,70,...,45108,NaN,Returned to Compliance,45134.0,SOX,State Compliance achieved,NaN,NaN,3,45244
9,NE3120840,EAGLES NEST ESTATES,Region 7,Nebraska,CWS,State,Ground water,Active,NaN,52,...,45108,45199.0,Known,NaN,NaN,NaN,NaN,NaN,2,45244

In [10]:
# Utilizing the .tail() function to view the last 5 rows of the data

nebraska_data.tail(5)

,pws_id,pws_name,epa_region_code,primacy_agency,pws_type,owner_type,primary_source,activity_status,season_end_date,population,...,season_start_date,last_reported,submission_quarter,return_to_compliance_date,contaminant_code,submission_year,major_violation,connections,first_reported,submission_year.1
12718,NE3117308,"PENDER, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,1100,...,28444,28473.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12719,NE3115902,"GOEHNER, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,185,...,28422,28452.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12720,NE3115905,"SEWARD, CITY OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,7500,...,28412,28442.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12721,NE3105907,"MILLIGAN, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,244,...,28321,28351.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494
12722,NE3115503,"CERESCO, VILLAGE OF",Region 7,Nebraska,CWS,State,Ground water,Active,NaN,919,...,28298,28327.0,Known,NaN,NaN,NaN,NaN,NaN,2,29494

In [12]:
# This gives the names of all the columns from the CSV file so that we can reference them later on

nebraska_data.columns

Index(['pws_id', 'pws_name', 'epa_region_code', 'primacy_agency', 'pws_type',
       'owner_type', 'primary_source', 'activity_status', 'season_end_date',
       'population', 'rule_name', 'violation_code', 'violation_type',
       'violation_category', 'health_based', 'contaminant',
       'season_start_date', 'last_reported', 'submission_quarter',
       'return_to_compliance_date', 'contaminant_code', 'submission_year',
       'major_violation', 'connections', 'first_reported',
       'submission_year.1'],
      dtype='object')

## Summarizing Data

This section will summarize the data so that we can complete the tasks outlined for Project #1.

In [14]:
# Grouping the data file by PWS Type and Contaminant

grouped_nebraska_data = nebraska_data.groupby(['pws_type' , 'contaminant']).size()

# Print the new grouped data, which is called "grouped_nebraska_data"

print(grouped_nebraska_data)

pws_type  contaminant
CWS       1,1,1-Trichloroethane                                      10
          1,1,2-Trichloroethane                                       4
          1,1-Dichloroethylene                                       10
          1,2,4-Trichlorobenzene                                     10
          1,2-DIBROMO-3-CHLOROPROPANE                                 2
                                                                   ...
TNCWS     Nitrate                                                    23
          Nitrate-Nitrite                                           508
          Public Notice                                             213
          Revised Total Coliform Rule                               376
          Stage 1 Disinfectants and Disinfection Byproducts Rule      6
Length: 118, dtype: int64

In [16]:
# Creating a new data summary: Save the data to a variable by using the .reset_index(name = '')
# This code will give us the number of violations for each contaminant by the type of water system

summary = grouped_nebraska_data.reset_index(name = 'n')

# Print summary
print(summary)

    pws_type                                        contaminant    n
0        CWS                              1,1,1-Trichloroethane   10
1        CWS                              1,1,2-Trichloroethane    4
2        CWS                               1,1-Dichloroethylene   10
3        CWS                             1,2,4-Trichlorobenzene   10
4        CWS                        1,2-DIBROMO-3-CHLOROPROPANE    2
..       ...                                                ...  ...
113    TNCWS                                            Nitrate   23
114    TNCWS                                    Nitrate-Nitrite  508
115    TNCWS                                      Public Notice  213
116    TNCWS                        Revised Total Coliform Rule  376
117    TNCWS  Stage 1 Disinfectants and Disinfection Byprodu...    6

[118 rows x 3 columns]

In [18]:
# Statistical Summary using the .agg() function. 
# This groups the data by contaminant and then finds the maximum (max), minimum (min), mean (mean), and median (median) of the data. 

stat_summary = summary.groupby('contaminant').agg(max=('n', 'max'),
                                                min=('n', 'min'),
                                                mean=('n', 'mean'),
                                                median=('n', 'median'))

print(stat_summary)

                             max  min  mean  median
contaminant
1,1,1-Trichloroethane         10   10  10.0    10.0
1,1,2-Trichloroethane          4    4   4.0     4.0
1,1-Dichloroethylene          10   10  10.0    10.0
1,2,4-Trichlorobenzene        10   10  10.0    10.0
1,2-DIBROMO-3-CHLOROPROPANE    2    2   2.0     2.0
...                          ...  ...   ...     ...
Xylenes, Total                 8    8   8.0     8.0
cis-1,2-Dichloroethylene       4    4   4.0     4.0
o-Dichlorobenzene             10   10  10.0    10.0
p-Dichlorobenzene             10   10  10.0    10.0
trans-1,2-Dichloroethylene    10   10  10.0    10.0

[85 rows x 4 columns]

# Request #1

In [20]:
#This is used to group by pws type and then find statistical data for each type
# This is used for Request 1 in the Lab Report
stat_summary = summary.groupby('pws_type').agg(max=('n', 'max'),
                                                min=('n', 'min'),
                                                mean=('n', 'mean'),
                                                median=('n', 'median'))

print(stat_summary)

           max  min        mean  median
pws_type
CWS       5348    1  103.423529    10.0
NTNCWS     315    1   29.041667     1.0
TNCWS     2059    5  359.444444    29.0

In [24]:
# Summary for PWS type and Contaminant using the .grouby .size() and .reset_index functions.
# This counts violations for each combination of PWS type and contaminant (this is the same summary as above).
summary = nebraska_data.groupby(['pws_type', 'contaminant']).size().reset_index(name = 'n')

# This calculates the total violations per contaminant using the .sum() function.
total_per_contaminant=summary.groupby('contaminant')['n'].sum().reset_index(name = 'total')

# This merges the total violations per contaminant back to the summary by using the .merge() function.
summary = summary.merge(total_per_contaminant, on='contaminant')

# This calculates the percentage of violations for each contaminant for each PWS type.
summary['percent_of_total'] = (summary['n'] / summary['total'])*100

print(summary)

## Creates a pivot table to summarize the data by using the function .pivot
summary_pivot = summary.pivot(index = 'contaminant', columns = 'pws_type', values = 'percent_of_total')
print(summary_pivot)

# This exports our summary_pivot to a csv
summary_pivot.to_csv('percentages.csv', index = False)

    pws_type                  contaminant   n  total  percent_of_total
0        CWS        1,1,1-Trichloroethane  10     10             100.0
1        CWS        1,1,2-Trichloroethane   4      4             100.0
2        CWS         1,1-Dichloroethylene  10     10             100.0
3        CWS       1,2,4-Trichlorobenzene  10     10             100.0
4        CWS  1,2-DIBROMO-3-CHLOROPROPANE   2      2             100.0
..       ...                          ...  ..    ...               ...
113      CWS               Xylenes, Total   8      8             100.0
114      CWS     cis-1,2-Dichloroethylene   4      4             100.0
115      CWS            o-Dichlorobenzene  10     10             100.0
116      CWS            p-Dichlorobenzene  10     10             100.0
117      CWS   trans-1,2-Dichloroethylene  10     10             100.0

[118 rows x 5 columns]
pws_type                       CWS  NTNCWS  TNCWS
contaminant
1,1,1-Trichloroethane        100.0     NaN    NaN
1,1,2-Trichloroethane        100.0     NaN    NaN
1,1-Dichloroethylene         100.0     NaN    NaN
1,2,4-Trichlorobenzene       100.0     NaN    NaN
1,2-DIBROMO-3-CHLOROPROPANE  100.0     NaN    NaN
...                            ...     ...    ...
Xylenes, Total               100.0     NaN    NaN
cis-1,2-Dichloroethylene     100.0     NaN    NaN
o-Dichlorobenzene            100.0     NaN    NaN
p-Dichlorobenzene            100.0     NaN    NaN
trans-1,2-Dichloroethylene   100.0     NaN    NaN

[85 rows x 3 columns]

## Filtering Data

This section of code filters data for what we need for our analysis.

In [22]:
#Filtering Data for only Active Systems
active_systems = nebraska_data[(nebraska_data['activity_status'] == "Active")]

print(active_systems)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

In [26]:
#Filtering Data for only Active System using the .query() function.

active_system_query = nebraska_data.query('activity_status == "Active"')

print(active_system_query)

          pws_id                        pws_name epa_region_code  \
0      NE3120835                      LITTLE USA        Region 7
1      NE3121452                  ELKHORN SHORES        Region 7
2      NE3121245                   DRIFTWOOD INN        Region 7
3      NE3150475  TYSON FRESH MEATS INC  MADISON        Region 7
4      NE3121401   SANDY POINTE LAKE DEVELOPMENT        Region 7
...          ...                             ...             ...
12718  NE3117308              PENDER, VILLAGE OF        Region 7
12719  NE3115902             GOEHNER, VILLAGE OF        Region 7
12720  NE3115905                 SEWARD, CITY OF        Region 7
12721  NE3105907            MILLIGAN, VILLAGE OF        Region 7
12722  NE3115503             CERESCO, VILLAGE OF        Region 7

      primacy_agency pws_type owner_type primary_source activity_status  \
0           Nebraska    TNCWS      State   Ground water          Active
1           Nebraska    TNCWS      State   Ground water          Active
2           Nebraska    TNCWS      State   Ground water          Active
3           Nebraska   NTNCWS      State   Ground water          Active
4           Nebraska      CWS      State   Ground water          Active
...              ...      ...        ...            ...             ...
12718       Nebraska      CWS      State   Ground water          Active
12719       Nebraska      CWS      State   Ground water          Active
12720       Nebraska      CWS      State   Ground water          Active
12721       Nebraska      CWS      State   Ground water          Active
12722       Nebraska      CWS      State   Ground water          Active

       season_end_date  population  ... season_start_date last_reported  \
0                  NaN         200  ...             45170       45199.0
1                  NaN          35  ...             45170       45199.0
2                  NaN          25  ...             45170       45199.0
3                  NaN        1100  ...             45170       45199.0
4                  NaN         100  ...             45139       45169.0
...                ...         ...  ...               ...           ...
12718              NaN        1100  ...             28444       28473.0
12719              NaN         185  ...             28422       28452.0
12720              NaN        7500  ...             28412       28442.0
12721              NaN         244  ...             28321       28351.0
12722              NaN         919  ...             28298       28327.0

      submission_quarter return_to_compliance_date contaminant_code  \
0                  Known                       NaN              NaN
1                  Known                       NaN              NaN
2                  Known                       NaN              NaN
3                  Known                       NaN              NaN
4                  Known                       NaN              SIF
...                  ...                       ...              ...
12718              Known                       NaN              NaN
12719              Known                       NaN              NaN
12720              Known                       NaN              NaN
12721              Known                       NaN              NaN
12722              Known                       NaN              NaN

                          submission_year  major_violation  connections  \
0                                     NaN                Y          NaN
1                                     NaN                Y          NaN
2                                     NaN                Y          NaN
3                                     NaN                Y          NaN
4      State Public Notification received                Y          NaN
...                                   ...              ...          ...
12718                                 NaN              NaN          NaN
12719                                 NaN              NaN          NaN
12720                                 NaN              NaN          NaN
12721                                 NaN              NaN          NaN
12722                                 NaN              NaN          NaN

      first_reported  submission_year.1
0                  3              45244
1                  3              45244
2                  3              45244
3                  3              45244
4                  3              45244
...              ...                ...
12718              2              29494
12719              2              29494
12720              2              29494
12721              2              29494
12722              2              29494

[12723 rows x 26 columns]

In [28]:
#Double Filtering: This filters the data by more than one attribute. 
#Below shows the systems which are active systems and systems with a Maximum Contaminant Level Violation.

subset_filter = nebraska_data[(nebraska_data['activity_status'] == "Active") & 
            (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Average")]
print(subset_filter)
print(subset_filter['violation_type'])

          pws_id                   pws_name epa_region_code primacy_agency  \
9      NE3120840        EAGLES NEST ESTATES        Region 7       Nebraska
17     NE3121047  THE CROSSING AT LEXINGTON        Region 7       Nebraska
18     NE3120182  BUFFALO RIDGE GOLF COURSE        Region 7       Nebraska
26     NE3114106          COLLEGE VIEW PARK        Region 7       Nebraska
27     NE3114505        LEBANON, VILLAGE OF        Region 7       Nebraska
...          ...                        ...             ...            ...
12579  NE3115717            GERING, CITY OF        Region 7       Nebraska
12580  NE3108503        TRENTON, VILLAGE OF        Region 7       Nebraska
12581  NE3110905           WAVERLY, CITY OF        Region 7       Nebraska
12582  NE3104710        OVERTON, VILLAGE OF        Region 7       Nebraska
12583  NE3103701          SCHUYLER, CITY OF        Region 7       Nebraska

      pws_type owner_type primary_source activity_status  season_end_date  \
9          CWS      State   Ground water          Active              NaN
17       TNCWS      State   Ground water          Active              NaN
18       TNCWS      State   Ground water          Active              NaN
26         CWS      State   Ground water          Active              NaN
27         CWS      State   Ground water          Active              NaN
...        ...        ...            ...             ...              ...
12579      CWS      State   Ground water          Active              NaN
12580      CWS      State   Ground water          Active              NaN
12581      CWS      State   Ground water          Active              NaN
12582      CWS      State   Ground water          Active              NaN
12583      CWS      State   Ground water          Active              NaN

       population  ... season_start_date last_reported  \
9              52  ...             45108       45199.0
17            499  ...             45108       45199.0
18             85  ...             45108       45199.0
26            150  ...             45108       45199.0
27             58  ...             45108       45199.0
...           ...  ...               ...           ...
12579        8500  ...             30590       32050.0
12580         560  ...             30590       32050.0
12581        4279  ...             30590       32050.0
12582         600  ...             30590       32050.0
12583        6547  ...             30590       32050.0

           submission_quarter return_to_compliance_date contaminant_code  \
9                       Known                       NaN              NaN
17                      Known                       NaN              NaN
18                      Known                       NaN              NaN
26                      Known                       NaN              SFL
27                      Known                       NaN              SFL
...                       ...                       ...              ...
12579  Returned to Compliance                   44197.0              EOX
12580  Returned to Compliance                   44197.0              EOX
12581  Returned to Compliance                   44197.0              EOX
12582  Returned to Compliance                   44197.0              EOX
12583  Returned to Compliance                   44197.0              EOX

                                         submission_year  major_violation  \
9                                                    NaN              NaN
17                                                   NaN              NaN
18                                                   NaN              NaN
26     State Administrative/Compliance Order without ...              NaN
27     State Administrative/Compliance Order without ...              NaN
...                                                  ...              ...
12579                        Federal Compliance achieved              NaN
12580                        Federal Compliance achieved              NaN
12581                        Federal Compliance achieved              NaN
12582                        Federal Compliance achieved              NaN
12583                        Federal Compliance achieved              NaN

       connections first_reported  submission_year.1
9              NaN              2              45244
17             NaN              1              45244
18             NaN              1              45244
26             NaN              2              45244
27             NaN              2              45244
...            ...            ...                ...
12579          NaN              2              31320
12580          NaN              2              31320
12581          NaN              2              31320
12582          NaN              2              31320
12583          NaN              2              31320

[1583 rows x 26 columns]
9        Maximum Contaminant Level Violation, Average
17       Maximum Contaminant Level Violation, Average
18       Maximum Contaminant Level Violation, Average
26       Maximum Contaminant Level Violation, Average
27       Maximum Contaminant Level Violation, Average
                             ...
12579    Maximum Contaminant Level Violation, Average
12580    Maximum Contaminant Level Violation, Average
12581    Maximum Contaminant Level Violation, Average
12582    Maximum Contaminant Level Violation, Average
12583    Maximum Contaminant Level Violation, Average
Name: violation_type, Length: 1583, dtype: object

In [96]:
#Filtering the Data: This applies multiple filters
# Filtering for "Maximum Contaminant Level, Average" OR "Maximum Contaminant Level, Single Sample"
subset_filter2 = nebraska_data[(nebraska_data['activity_status']=="Active") &
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Average") |                   
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation,Single Sample")]

# print only the column 'violation_type
print(subset_filter2['violation_type'])

# Extracting the subset to CSV to visualize the columns
subset_filter2.to_csv('subset_filter2.csv', index=False)

9        Maximum Contaminant Level Violation, Average
17       Maximum Contaminant Level Violation, Average
18       Maximum Contaminant Level Violation, Average
26       Maximum Contaminant Level Violation, Average
27       Maximum Contaminant Level Violation, Average
                             ...
12579    Maximum Contaminant Level Violation, Average
12580    Maximum Contaminant Level Violation, Average
12581    Maximum Contaminant Level Violation, Average
12582    Maximum Contaminant Level Violation, Average
12583    Maximum Contaminant Level Violation, Average
Name: violation_type, Length: 1583, dtype: object

In [30]:
# Step 1: Filter based on Activity Status and Population 
subset_client = nebraska_data[(nebraska_data['activity_status'] == "Active") &
                (nebraska_data['population'] <= 10000)]

# Step 2: Get the violations for 1) Type of Water System 2) Source Water Type, and 3) Contaminant
subset_client_table = subset_client.groupby(['pws_type','primary_source','contaminant']).size().reset_index(name = 'n')

# Step 3: Calculate the sum of violations using the .agg() function
analysis1 = subset_client_table.groupby(['pws_type','primary_source','contaminant']).agg(sum = ('n', 'sum'))

print(analysis1)

                                                                                         sum
pws_type primary_source                                     contaminant
CWS      Ground water                                       1,1,1-Trichloroethane         10
                                                            1,1,2-Trichloroethane          4
                                                            1,1-Dichloroethylene           9
                                                            1,2,4-Trichlorobenzene        10
                                                            1,2-DIBROMO-3-CHLOROPROPANE    2
...                                                                                      ...
TNCWS    Purchased ground water under influence of surfa... Public Notice                  5
                                                            Revised Total Coliform Rule    4
         Surface water purchased                            Coliform (TCR)                82
                                                            Public Notice                  3
                                                            Revised Total Coliform Rule   18

[168 rows x 1 columns]

# Alternative Approach Using Functions

1. Very Small: 500 or less
2. Small: 501 - 3,300
3. Medium: 3,301 - 10,000
4. Large: 10,001 - 100,000
5. Very Large: Greater than 100,000

# Request #2

In [98]:
# This is used for Request #2 
#Define Function
# This function will define each pws by a population category
def assign_category(x):
    if x <= 500:
        return "very small"
    elif 501 <= x <= 3300:
        return "small"
    elif 3301 <= x <= 10000:
        return "medium"
    elif 10001 <= x <= 100000:
        return "large"
    else:
        return "very large"

# Apply Function
nebraska_data['pop_category'] = nebraska_data['population'].apply(assign_category)

print(nebraska_data['pop_category'])

nebraska_data.to_csv('nebraska_data_categroy.csv', index=False)

0        very small
1        very small
2        very small
3             small
4        very small
            ...
12718         small
12719    very small
12720        medium
12721    very small
12722         small
Name: pop_category, Length: 12723, dtype: object

In [34]:
# This code groups by pws type, contaminant, and population cateogory
# This is used for Request #2
subset2 = nebraska_data[(nebraska_data['activity_status'] == "Active")]
summary2 = nebraska_data.groupby(['pws_type', 'contaminant','pop_category']).size().reset_index(name = 'n')
summary2.to_csv("Request2_Summary.csv")
print(summary2)

    pws_type                                        contaminant pop_category  \
0        CWS                              1,1,1-Trichloroethane        small
1        CWS                              1,1,1-Trichloroethane   very small
2        CWS                              1,1,2-Trichloroethane        small
3        CWS                              1,1,2-Trichloroethane   very small
4        CWS                               1,1-Dichloroethylene        large
..       ...                                                ...          ...
218    TNCWS                                      Public Notice        small
219    TNCWS                                      Public Notice   very small
220    TNCWS                        Revised Total Coliform Rule        small
221    TNCWS                        Revised Total Coliform Rule   very small
222    TNCWS  Stage 1 Disinfectants and Disinfection Byprodu...   very small

       n
0      8
1      2
2      2
3      2
4      1
..   ...
218    2
219  211
220    3
221  373
222    6

[223 rows x 4 columns]

# Request #3

In [115]:
#This section of code is for Request #3
# This filters by only CWS, small, and active systems
# Then is shows only MCL (Maximum Contaminant Levels) and then displays the contaminant name 
# Then it exports that to a csv to use for table use

subset_filter2 = nebraska_data[(nebraska_data['activity_status']=="Active") &                   
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Single Sample") |
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Average") |
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, E. coli (RTCR)") |
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Monthly (TCR)") |
                    (nebraska_data['violation_type'] == "Maximum Contaminant Level Violation, Acute (TCR)")]

summary3 = subset_filter2.groupby(['primary_source', 'violation_type', 'pop_category', 'pws_type', "contaminant"]).size().reset_index(name='quantity')
summary4 = summary3[(summary3['pop_category'] == "small")]
summary5 = summary4[(summary4['pws_type'] == "CWS")]
print(summary5)


summary5.to_csv("Request#3-Summary.csv")

                                        primary_source  \
3                                         Ground water
29                                        Ground water
30                                        Ground water
31                                        Ground water
32                                        Ground water
33                                        Ground water
34                                        Ground water
35                                        Ground water
36                                        Ground water
37                                        Ground water
38                                        Ground water
61                                        Ground water
69                                        Ground water
79                                        Ground water
80                                        Ground water
81                                        Ground water
82                                        Ground water
83                                        Ground water
84                                        Ground water
100                             Ground water purchased
102                             Ground water purchased
103                             Ground water purchased
104                             Ground water purchased
105                             Ground water purchased
114                             Ground water purchased
116                             Ground water purchased
120                             Ground water purchased
130       Groundwater under influence of surface water
132  Purchased ground water under influence of surf...
133  Purchased ground water under influence of surf...
135  Purchased ground water under influence of surf...
138                                      Surface water
139                                      Surface water
141                            Surface water purchased
143                            Surface water purchased
146                            Surface water purchased

                                        violation_type pop_category pws_type  \
3     Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
29        Maximum Contaminant Level Violation, Average        small      CWS
30        Maximum Contaminant Level Violation, Average        small      CWS
31        Maximum Contaminant Level Violation, Average        small      CWS
32        Maximum Contaminant Level Violation, Average        small      CWS
33        Maximum Contaminant Level Violation, Average        small      CWS
34        Maximum Contaminant Level Violation, Average        small      CWS
35        Maximum Contaminant Level Violation, Average        small      CWS
36        Maximum Contaminant Level Violation, Average        small      CWS
37        Maximum Contaminant Level Violation, Average        small      CWS
38        Maximum Contaminant Level Violation, Average        small      CWS
61   Maximum Contaminant Level Violation, E. coli (...        small      CWS
69   Maximum Contaminant Level Violation, Monthly (...        small      CWS
79   Maximum Contaminant Level Violation, Single Sa...        small      CWS
80   Maximum Contaminant Level Violation, Single Sa...        small      CWS
81   Maximum Contaminant Level Violation, Single Sa...        small      CWS
82   Maximum Contaminant Level Violation, Single Sa...        small      CWS
83   Maximum Contaminant Level Violation, Single Sa...        small      CWS
84   Maximum Contaminant Level Violation, Single Sa...        small      CWS
100   Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
102       Maximum Contaminant Level Violation, Average        small      CWS
103       Maximum Contaminant Level Violation, Average        small      CWS
104       Maximum Contaminant Level Violation, Average        small      CWS
105       Maximum Contaminant Level Violation, Average        small      CWS
114  Maximum Contaminant Level Violation, E. coli (...        small      CWS
116  Maximum Contaminant Level Violation, Monthly (...        small      CWS
120  Maximum Contaminant Level Violation, Single Sa...        small      CWS
130  Maximum Contaminant Level Violation, Monthly (...        small      CWS
132   Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
133  Maximum Contaminant Level Violation, E. coli (...        small      CWS
135  Maximum Contaminant Level Violation, Monthly (...        small      CWS
138       Maximum Contaminant Level Violation, Average        small      CWS
139       Maximum Contaminant Level Violation, Average        small      CWS
141   Maximum Contaminant Level Violation, Acute (TCR)        small      CWS
143       Maximum Contaminant Level Violation, Average        small      CWS
146  Maximum Contaminant Level Violation, Monthly (...        small      CWS

                         contaminant  quantity
3                     Coliform (TCR)        44
29                1,2-Dichloroethane         1
30                           Arsenic        81
31              Carbon tetrachloride         4
32   Combined Radium (-226 and -228)         6
33                  Combined Uranium        86
34    Gross Alpha, Excl. Radon and U         6
35                           Nitrate        20
36                   Nitrate-Nitrite       139
37                          Selenium        66
38               Tetrachloroethylene         7
61       Revised Total Coliform Rule         9
69                    Coliform (TCR)       899
79              Carbon tetrachloride         1
80                          Fluoride         2
81                           Nitrate        13
82                   Nitrate-Nitrite       136
83                          Selenium        51
84               Tetrachloroethylene         1
100                   Coliform (TCR)         7
102                          Arsenic         1
103                 Combined Uranium       105
104   Gross Alpha, Excl. Radon and U         2
105                          Nitrate         1
114      Revised Total Coliform Rule         1
116                   Coliform (TCR)        77
120                          Nitrate         1
130                   Coliform (TCR)         2
132                   Coliform (TCR)         1
133      Revised Total Coliform Rule         1
135                   Coliform (TCR)         2
138                             TTHM        33
139    Total Haloacetic Acids (HAA5)         1
141                   Coliform (TCR)         1
143                             TTHM        11
146                   Coliform (TCR)        10